name: Deployment

on:
  workflow_dispatch:
  push:
    # tags:
    #   - "v*.*.*"

env:
  UNIT: com.narumi.pyrumi-bot
  WORKDIR: /Users/narumi/services/pyrumi-bot
  PLIST_PATH: /Users/narumi/Library/LaunchAgents

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Stop and disable service
        continue-on-error: true
        working-directory: ${{ env.PLIST_PATH }}
        run: |
          launchctl stop ${{ env.UNIT }}
          launchctl unload pyrumi-bot.plist

      - name: Create .env file
        run: |
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} > .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          echo WOLFRAM_ALPHA_APPID=${{ secrets.WOLFRAM_ALPHA_APPID }} >> .env

      - name: Install
        run: |
          pip install .

      - name: Copy files
        run: |
          mkdir -p ${{ env.WORKDIR }} 
          cp .env ${{ env.WORKDIR }}
          cp pyrumi-bot.plist ${{ env.PLIST_PATH }}

      - name: Start service
        working-directory: ${{ env.PLIST_PATH }}
        run: |
          launchctl load -w pyrumi-bot.plist
          launchctl start ${{ env.UNIT }}
